from enum import Enum


class Fogao(Enum):
    LIGAR = 'LIGAR FOGÃO'
    DESLIGAR = 'DESLIGAR FOGÃO'


class Frigideira(Enum):
    COLOCAR_NO_FOGAO = 'COLOCAR NO FOGÃO'
    RETIRAR_DO_FOGAO = 'RETIRAR DO FOGÃO'
    TRANSFERIR_CALOR = 'TRANSFERIR CALOR'
    INTERROMPER_CALOR = 'INTERROMPER CALOR'


class Ingrediente(Enum):
    COLOCAR_NA_FRIGIDEIRA = 'COLOCAR NA FRIGIDEIRA'
    RETIRAR_DA_FRIGIDEIRA = 'RETIRAR DA FRIGIDEIRA'
